name: "CD"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
